ccopy_reg
_reconstructor
p1
(cfeedparser
FeedParserDict
p2
c__builtin__
dict
p3
(dp4
S'feed'
p5
g1
(g2
g3
(dp6
S'title_detail'
p7
g1
(g2
g3
(dp8
S'base'
p9
Vhttp://www.reddit.com/r/DotA2.rss
p10
sS'type'
p11
Vtext/plain
p12
sS'language'
p13
NsS'value'
p14
VDota 2 on Reddit
p15
stRp16
sS'subtitle'
p17
VA subreddit for Dota 2, an action RTS game developed by Valve Corporation.
p18
sS'links'
p19
(lp20
g1
(g2
g3
(dp21
S'href'
p22
Vhttp://www.reddit.com/r/DotA2/
p23
sg11
Vtext/html
p24
sS'rel'
p25
Valternate
p26
stRp27
ag1
(g2
g3
(dp28
S'href'
p29
Vhttp://www.reddit.com/r/DotA2.rss
p30
sS'type'
p31
Vapplication/rss+xml
p32
sS'rel'
p33
Vself
p34
stRp35
asS'title'
p36
g15
sS'link'
p37
g23
sS'image'
p38
g1
(g2
g3
(dp39
S'title_detail'
p40
g1
(g2
g3
(dp41
g9
Vhttp://www.reddit.com/r/DotA2.rss
p42
sg11
g12
sg13
Nsg14
VDota 2 on Reddit
p43
stRp44
sg22
Vhttp://f.thumbs.redditmedia.com/N3DZWQMJeztjqrAY.png
p45
sg37
Vhttp://www.reddit.com/r/DotA2/
p46
sg19
(lp47
g1
(g2
g3
(dp48
g22
g46
sg11
g24
sg25
g26
stRp49
asg36
g43
stRp50
sS'subtitle_detail'
p51
g1
(g2
g3
(dp52
g9
Vhttp://www.reddit.com/r/DotA2.rss
p53
sg11
Vtext/html
p54
sg13
Nsg14
g18
stRp55
stRp56
sS'status'
p57
I200
sS'encoding'
p58
VUTF-8
p59
sS'bozo'
p60
I0
sS'headers'
p61
(dp62
S'content-length'
p63
S'12037'
p64
sS'x-xss-protection'
p65
S'1; mode=block'
p66
sS'x-content-type-options'
p67
S'nosniff'
p68
sS'content-encoding'
p69
S'gzip'
p70
sS'vary'
p71
S'accept-encoding'
p72
sS'server'
p73
S"'; DROP TABLE servertypes; --"
p74
sS'connection'
p75
S'close'
p76
sS'date'
p77
S'Fri, 11 Jul 2014 10:17:19 GMT'
p78
sS'x-frame-options'
p79
S'SAMEORIGIN'
p80
sS'content-type'
p81
S'text/xml; charset=UTF-8'
p82
ssS'version'
p83
Vrss20
p84
sg22
Vhttp://www.reddit.com/r/DotA2.rss
p85
sS'namespaces'
p86
(dp87
S''
Vhttp://www.w3.org/2005/Atom
p88
sS'media'
p89
Vhttp://search.yahoo.com/mrss/
p90
sS'dc'
p91
Vhttp://purl.org/dc/elements/1.1/
p92
ssS'entries'
p93
(lp94
g1
(g2
g3
(dp95
S'summary_detail'
p96
g1
(g2
g3
(dp97
g9
Vhttp://www.reddit.com/r/DotA2.rss
p98
sg11
g54
sg13
Nsg14
V<!-- SC_OFF --><div class="md"><h3>The International 2014</h3> <h2>Organized and hosted by Valve Corporation</h2> <h2>Sponsored by Valve Corporation, The Compendium</h2> <hr /> <p><strong>Need info on the event? Check out our <a href="http://www.reddit.com/r/DotA2/wiki/events/ti4">Survival Guide</a></strong></p> <p><strong>Check out the Day 3 <a href="http://redd.it/2ac6qf">Live Discussion</a>.</strong></p> <h4>VODs can be found on the Watch tab of the TI Tournament Site</h4> <h3><a href="http://www.dota2.com/international/watch/July10/">Click &quot;Stream Navigation&quot; for a full list of Today's Games or select a match below</a></h3> <hr /> <h3>Standings after Day 3:</h3> <table><thead> <tr> <th align="left">Round Robin Day 2</th> <th align="center"><a href="http://www.reddit.com/nbsp"></a></th> </tr> </thead><tbody> <tr> <td align="left"><a href="http://www.reddit.com/cn" title="China"></a> Vici Gaming</td> <td align="center">&nbsp; 7-1 &nbsp;</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/cn" title="China"></a> Team DK</td> <td align="center">6-3</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/cn" title="China"></a> Invictus Gaming</td> <td align="center">6-3</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/us" title="United States"></a> Evil Geniuses</td> <td align="center">6-3</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/ua" title="Ukraine"></a> Natus Vincere EU</td> <td align="center">5-3</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/my" title="Malaysia"></a> Titan</td> <td align="center">5-4</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/wo" title="World"></a> Cloud9</td> <td align="center">5-4</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/us" title="United States"></a> Team Liquid</td> <td align="center">5-4</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/cn" title="China"></a> Newbee</td> <td align="center">5-5</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/se" title="Sweden"></a> The Alliance</td> <td align="center">4-5</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/eu" title="Europe"></a> Fnatic</td> <td align="center">4-5</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/us" title="United States"></a> Natus Vincere US</td> <td align="center">4-5</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/ru" title="Russia"></a> Team Empire</td> <td align="center">3-6</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/cn" title="China"></a> LGD Gaming</td> <td align="center">3-6</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/de" title="Germany"></a> mousesports</td> <td align="center">2-7</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/my" title="Malaysia"></a> Arrow Gaming</td> <td align="center">2-8</td> </tr> </tbody></table> <hr /> <h3>Full Results:</h3> <p>Check out the full schedule and results from today's matches here: <a href="http://redd.it/2ac6qf">Day 3 Discussion</a></p> </div><!-- SC_ON --> submitted by <a href="http://www.reddit.com/user/D2TournamentThreads"> D2TournamentThreads </a> <br /> <a href="http://www.reddit.com/r/DotA2/comments/2aeawq/the_international_2014_playoffs_post_day_3/">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2aeawq/the_international_2014_playoffs_post_day_3/">[283 comments]</a>
p99
stRp100
sg19
(lp101
g1
(g2
g3
(dp102
g22
Vhttp://www.reddit.com/r/DotA2/comments/2aeawq/the_international_2014_playoffs_post_day_3/
p103
sg11
g24
sg25
g26
stRp104
asS'published_parsed'
p105
ctime
struct_time
p106
((I2014
I7
I11
I3
I56
I42
I4
I192
I0
t(dtRp107
sg36
VThe International 2014 Playoffs Post Day 3 Discussion
p108
sS'summary'
p109
g99
sS'guidislink'
p110
I00
sS'title_detail'
p111
g1
(g2
g3
(dp112
g9
Vhttp://www.reddit.com/r/DotA2.rss
p113
sg11
g12
sg13
Nsg14
g108
stRp114
sg37
g103
sS'published'
p115
VFri, 11 Jul 2014 03:56:42 +0000
p116
sS'id'
p117
Vhttp://www.reddit.com/r/DotA2/comments/2aeawq/the_international_2014_playoffs_post_day_3/
p118
stRp119
ag1
(g2
g3
(dp120
S'summary_detail'
p121
g1
(g2
g3
(dp122
g9
Vhttp://www.reddit.com/r/DotA2.rss
p123
sg11
g54
sg13
Nsg14
Vsubmitted by <a href="http://www.reddit.com/user/Randomd0g"> Randomd0g </a> <br /> <a href="http://www.reddit.com/r/DotA2/comments/2adgzw/suggestion_if_a_team_wins_3_internationals_they/">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2adgzw/suggestion_if_a_team_wins_3_internationals_they/">[155 comments]</a>
p124
stRp125
sg19
(lp126
g1
(g2
g3
(dp127
g22
Vhttp://www.reddit.com/r/DotA2/comments/2adgzw/suggestion_if_a_team_wins_3_internationals_they/
p128
sg11
g24
sg25
g26
stRp129
asg105
g106
((I2014
I7
I10
I22
I37
I10
I3
I191
I0
t(dtRp130
sg36
VSuggestion - if a team wins 3 internationals they also win a block of cheese along with the aegis.
p131
sg109
g124
sg110
I00
sS'title_detail'
p132
g1
(g2
g3
(dp133
g9
Vhttp://www.reddit.com/r/DotA2.rss
p134
sg11
g12
sg13
Nsg14
g131
stRp135
sg37
g128
sg115
VThu, 10 Jul 2014 22:37:10 +0000
p136
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2adgzw/suggestion_if_a_team_wins_3_internationals_they/
p137
stRp138
ag1
(g2
g3
(dp139
S'summary_detail'
p140
g1
(g2
g3
(dp141
g9
Vhttp://www.reddit.com/r/DotA2.rss
p142
sg11
g54
sg13
Nsg14
Vsubmitted by <a href="http://www.reddit.com/user/volcanicthor"> volcanicthor </a> <br /> <a href="http://i.imgur.com/azJv93r.jpg?1">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2adw9u/s4s_art_in_the_a_vs_empire/">[52 comments]</a>
p143
stRp144
sg19
(lp145
g1
(g2
g3
(dp146
g22
Vhttp://www.reddit.com/r/DotA2/comments/2adw9u/s4s_art_in_the_a_vs_empire/
p147
sg11
g24
sg25
g26
stRp148
asg105
g106
((I2014
I7
I11
I1
I13
I45
I4
I192
I0
t(dtRp149
sg36
VS4's art in the [A] vs Empire
p150
sg109
g143
sg110
I00
sS'title_detail'
p151
g1
(g2
g3
(dp152
g9
Vhttp://www.reddit.com/r/DotA2.rss
p153
sg11
g12
sg13
Nsg14
g150
stRp154
sg37
g147
sg115
VFri, 11 Jul 2014 01:13:45 +0000
p155
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2adw9u/s4s_art_in_the_a_vs_empire/
p156
stRp157
ag1
(g2
g3
(dp158
S'summary_detail'
p159
g1
(g2
g3
(dp160
g9
Vhttp://www.reddit.com/r/DotA2.rss
p161
sg11
g54
sg13
Nsg14
Vsubmitted by <a href="http://www.reddit.com/user/TheOneAndOnlyTristan"> TheOneAndOnlyTristan </a> <br /> <a href="https://twitter.com/YouPorn/status/487359454506397697">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2adqqo/coming_ti5_youporn_sponsored_team/">[386 comments]</a>
p162
stRp163
sg19
(lp164
g1
(g2
g3
(dp165
g22
Vhttp://www.reddit.com/r/DotA2/comments/2adqqo/coming_ti5_youporn_sponsored_team/
p166
sg11
g24
sg25
g26
stRp167
asg105
g106
((I2014
I7
I11
I0
I15
I52
I4
I192
I0
t(dtRp168
sg36
VComing TI5: Youporn sponsored Team
p169
sg109
g162
sg110
I00
sS'title_detail'
p170
g1
(g2
g3
(dp171
g9
Vhttp://www.reddit.com/r/DotA2.rss
p172
sg11
g12
sg13
Nsg14
g169
stRp173
sg37
g166
sg115
VFri, 11 Jul 2014 00:15:52 +0000
p174
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2adqqo/coming_ti5_youporn_sponsored_team/
p175
stRp176
ag1
(g2
g3
(dp177
S'summary_detail'
p178
g1
(g2
g3
(dp179
g9
Vhttp://www.reddit.com/r/DotA2.rss
p180
sg11
g54
sg13
Nsg14
Vsubmitted by <a href="http://www.reddit.com/user/ja_gern"> ja_gern </a> <br /> <a href="https://www.youtube.com/watch?feature=player_detailpage&amp;v=MisqMKRysxg">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2aeez9/classicjimmymp4/">[59 comments]</a>
p181
stRp182
sg19
(lp183
g1
(g2
g3
(dp184
g22
Vhttp://www.reddit.com/r/DotA2/comments/2aeez9/classicjimmymp4/
p185
sg11
g24
sg25
g26
stRp186
asg105
g106
((I2014
I7
I11
I4
I47
I46
I4
I192
I0
t(dtRp187
sg36
VClassicJimmy.mp4
p188
sg109
g181
sg110
I00
sS'title_detail'
p189
g1
(g2
g3
(dp190
g9
Vhttp://www.reddit.com/r/DotA2.rss
p191
sg11
g12
sg13
Nsg14
g188
stRp192
sg37
g185
sg115
VFri, 11 Jul 2014 04:47:46 +0000
p193
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2aeez9/classicjimmymp4/
p194
stRp195
ag1
(g2
g3
(dp196
S'summary_detail'
p197
g1
(g2
g3
(dp198
g9
Vhttp://www.reddit.com/r/DotA2.rss
p199
sg11
g54
sg13
Nsg14
V<!-- SC_OFF --><div class="md"><p>An update has been dispatched for the main client. More info will be edited in as it becomes available.</p> <hr /> <h2>Backend Update</h2> <ul> <li>New entries for a &quot;All-Star Draft&quot; game mode. Preparation for the All-Star match at TI.</li> <li>Techies now has a loadout entry and scaling.</li> </ul> <hr /> <h2>UI Updates</h2> <ul> <li>New advertisement banner for The International Bundle that tells you all the stuff you get when you buy the Compendium now and the upcoming items.</li> </ul> <hr /> <h2>Portrait Updates</h2> <ul> <li>Elemental Baby Roshans now have new portraits.</li> <li>All the full body portrait values now have been increased to have up to 5 decimal points for some reason. Complete accuracy. <em>For eg: what used to be &quot;-369.59&quot; is now &quot;-369.589996&quot;.</em></li> </ul> <hr /> <h2>PSA</h2> <p>A couple of points I see many threads about. As this thread gets some attention, I thought I'll mention them here.</p> <ul> <li>Pennants do not need to be equipped anymore. The fan slots have been removed. They work and do their job as long as they are owned by you and in your inventory.</li> <li>The Player Card Packs you get when spectating games are BONUS rewards for just watching. They are NOT the spectator rewards. So when it reads <em>&quot;50 people have won a prize ..&quot;</em> and you got a Player Card Pack, you did not get lucky.</li> </ul> <hr /> <ul> <li>Raw Schema: None</li> <li>No changelog yet.</li> </ul> <hr /> <p><strong>Patch Size:</strong> 32.3 Mb</p> </div><!-- SC_ON --> submitted by <a href="http://www.reddit.com/user/SirBelvedere"> SirBelvedere </a> <br /> <a href="http://www.reddit.com/r/DotA2/comments/2aebib/dota_2_update_main_client_july_10_2014/">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2aebib/dota_2_update_main_client_july_10_2014/">[190 comments]</a>
p200
stRp201
sg19
(lp202
g1
(g2
g3
(dp203
g22
Vhttp://www.reddit.com/r/DotA2/comments/2aebib/dota_2_update_main_client_july_10_2014/
p204
sg11
g24
sg25
g26
stRp205
asg105
g106
((I2014
I7
I11
I4
I3
I30
I4
I192
I0
t(dtRp206
sg36
VDota 2 Update - MAIN CLIENT - July 10, 2014
p207
sg109
g200
sg110
I00
sS'title_detail'
p208
g1
(g2
g3
(dp209
g9
Vhttp://www.reddit.com/r/DotA2.rss
p210
sg11
g12
sg13
Nsg14
g207
stRp211
sg37
g204
sg115
VFri, 11 Jul 2014 04:03:30 +0000
p212
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2aebib/dota_2_update_main_client_july_10_2014/
p213
stRp214
ag1
(g2
g3
(dp215
S'summary_detail'
p216
g1
(g2
g3
(dp217
g9
Vhttp://www.reddit.com/r/DotA2.rss
p218
sg11
g54
sg13
Nsg14
Vsubmitted by <a href="http://www.reddit.com/user/0x04b8"> 0x04b8 </a> <br /> <a href="http://www.youtube.com/watch?v=AGj1rtwKR9I">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2ae6uv/erik_johnson_never_spoken_russian_with_icefrog/">[166 comments]</a>
p219
stRp220
sg19
(lp221
g1
(g2
g3
(dp222
g22
Vhttp://www.reddit.com/r/DotA2/comments/2ae6uv/erik_johnson_never_spoken_russian_with_icefrog/
p223
sg11
g24
sg25
g26
stRp224
asg105
g106
((I2014
I7
I11
I3
I8
I56
I4
I192
I0
t(dtRp225
sg36
VErik Johnson: "Never spoken Russian with Icefrog"
p226
sg109
g219
sg110
I00
sS'title_detail'
p227
g1
(g2
g3
(dp228
g9
Vhttp://www.reddit.com/r/DotA2.rss
p229
sg11
g12
sg13
Nsg14
g226
stRp230
sg37
g223
sg115
VFri, 11 Jul 2014 03:08:56 +0000
p231
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2ae6uv/erik_johnson_never_spoken_russian_with_icefrog/
p232
stRp233
ag1
(g2
g3
(dp234
S'summary_detail'
p235
g1
(g2
g3
(dp236
g9
Vhttp://www.reddit.com/r/DotA2.rss
p237
sg11
g54
sg13
Nsg14
V<!-- SC_OFF --><div class="md"><p>I CAN'T BREATH I CANT SEE IM LOSING MY MIND!!!</p> </div><!-- SC_ON --> submitted by <a href="http://www.reddit.com/user/IIsWitty"> IIsWitty </a> <br /> <a href="http://www.reddit.com/r/DotA2/comments/2adhvx/narvi_vs_ig/">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2adhvx/narvi_vs_ig/">[578 comments]</a>
p238
stRp239
sg19
(lp240
g1
(g2
g3
(dp241
g22
Vhttp://www.reddit.com/r/DotA2/comments/2adhvx/narvi_vs_ig/
p242
sg11
g24
sg25
g26
stRp243
asg105
g106
((I2014
I7
I10
I22
I46
I20
I3
I191
I0
t(dtRp244
sg36
VNARV'I VS IG!!!
p245
sg109
g238
sg110
I00
sS'title_detail'
p246
g1
(g2
g3
(dp247
g9
Vhttp://www.reddit.com/r/DotA2.rss
p248
sg11
g12
sg13
Nsg14
g245
stRp249
sg37
g242
sg115
VThu, 10 Jul 2014 22:46:20 +0000
p250
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2adhvx/narvi_vs_ig/
p251
stRp252
ag1
(g2
g3
(dp253
S'summary_detail'
p254
g1
(g2
g3
(dp255
g9
Vhttp://www.reddit.com/r/DotA2.rss
p256
sg11
g54
sg13
Nsg14
V<!-- SC_OFF --><div class="md"><p>Best stream ever!</p> </div><!-- SC_ON --> submitted by <a href="http://www.reddit.com/user/VINCE_C_"> VINCE_C_ </a> <br /> <a href="http://www.reddit.com/r/DotA2/comments/2adgty/the_guy_that_came_with_the_multicast_idea/">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2adgty/the_guy_that_came_with_the_multicast_idea/">[129 comments]</a>
p257
stRp258
sg19
(lp259
g1
(g2
g3
(dp260
g22
Vhttp://www.reddit.com/r/DotA2/comments/2adgty/the_guy_that_came_with_the_multicast_idea/
p261
sg11
g24
sg25
g26
stRp262
asg105
g106
((I2014
I7
I10
I22
I35
I27
I3
I191
I0
t(dtRp263
sg36
VThe guy that came with the Multicast idea deserves a fucking medal.
p264
sg109
g257
sg110
I00
sS'title_detail'
p265
g1
(g2
g3
(dp266
g9
Vhttp://www.reddit.com/r/DotA2.rss
p267
sg11
g12
sg13
Nsg14
g264
stRp268
sg37
g261
sg115
VThu, 10 Jul 2014 22:35:27 +0000
p269
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2adgty/the_guy_that_came_with_the_multicast_idea/
p270
stRp271
ag1
(g2
g3
(dp272
S'summary_detail'
p273
g1
(g2
g3
(dp274
g9
Vhttp://www.reddit.com/r/DotA2.rss
p275
sg11
g54
sg13
Nsg14
Vsubmitted by <a href="http://www.reddit.com/user/Shincry"> Shincry </a> <br /> <a href="http://i.imgur.com/N8SmhG7.png">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2aby52/every_single_game_as_disruptor/">[337 comments]</a>
p276
stRp277
sg19
(lp278
g1
(g2
g3
(dp279
g22
Vhttp://www.reddit.com/r/DotA2/comments/2aby52/every_single_game_as_disruptor/
p280
sg11
g24
sg25
g26
stRp281
asg105
g106
((I2014
I7
I10
I13
I46
I7
I3
I191
I0
t(dtRp282
sg36
VEvery single game as disruptor
p283
sg109
g276
sg110
I00
sS'title_detail'
p284
g1
(g2
g3
(dp285
g9
Vhttp://www.reddit.com/r/DotA2.rss
p286
sg11
g12
sg13
Nsg14
g283
stRp287
sg37
g280
sg115
VThu, 10 Jul 2014 06:46:07 -0700
p288
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2aby52/every_single_game_as_disruptor/
p289
stRp290
ag1
(g2
g3
(dp291
S'summary_detail'
p292
g1
(g2
g3
(dp293
g9
Vhttp://www.reddit.com/r/DotA2.rss
p294
sg11
g54
sg13
Nsg14
V<!-- SC_OFF --><div class="md"><p>When we bought our VIP tickets, we weren't 100% sure what we were getting ourselves into. But this playoff experience has been nothing short of stunning. </p> <p>We all get to sit next to and interact with the players, coaches, managers &amp; personalities all day long. Full, high-quality catered buffets have been available for <em>all meals of the day</em>. Unlimited red bull and other energy drinks. The viewing setup is <em>perfect</em>.</p> <p>I'm just speechless. Just an all-around perfect experience. WP volvo</p> </div><!-- SC_ON --> submitted by <a href="http://www.reddit.com/user/Reead"> Reead </a> <br /> <a href="http://www.reddit.com/r/DotA2/comments/2aehgc/shoutout_to_valve_for_an_absolutely_amazing_vip/">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2aehgc/shoutout_to_valve_for_an_absolutely_amazing_vip/">[73 comments]</a>
p295
stRp296
sg19
(lp297
g1
(g2
g3
(dp298
g22
Vhttp://www.reddit.com/r/DotA2/comments/2aehgc/shoutout_to_valve_for_an_absolutely_amazing_vip/
p299
sg11
g24
sg25
g26
stRp300
asg105
g106
((I2014
I7
I11
I5
I18
I33
I4
I192
I0
t(dtRp301
sg36
VShoutout to Valve for an absolutely amazing VIP experience so far
p302
sg109
g295
sg110
I00
sS'title_detail'
p303
g1
(g2
g3
(dp304
g9
Vhttp://www.reddit.com/r/DotA2.rss
p305
sg11
g12
sg13
Nsg14
g302
stRp306
sg37
g299
sg115
VFri, 11 Jul 2014 05:18:33 +0000
p307
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2aehgc/shoutout_to_valve_for_an_absolutely_amazing_vip/
p308
stRp309
ag1
(g2
g3
(dp310
S'summary_detail'
p311
g1
(g2
g3
(dp312
g9
Vhttp://www.reddit.com/r/DotA2.rss
p313
sg11
g54
sg13
Nsg14
Vsubmitted by <a href="http://www.reddit.com/user/lokilize"> lokilize </a> <br /> <a href="http://i.imgur.com/qyzThiS.png">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2ac9v2/earrings_of_basilius/">[183 comments]</a>
p314
stRp315
sg19
(lp316
g1
(g2
g3
(dp317
g22
Vhttp://www.reddit.com/r/DotA2/comments/2ac9v2/earrings_of_basilius/
p318
sg11
g24
sg25
g26
stRp319
asg105
g106
((I2014
I7
I10
I15
I50
I1
I3
I191
I0
t(dtRp320
sg36
VEarrings of Basilius
p321
sg109
g314
sg110
I00
sS'title_detail'
p322
g1
(g2
g3
(dp323
g9
Vhttp://www.reddit.com/r/DotA2.rss
p324
sg11
g12
sg13
Nsg14
g321
stRp325
sg37
g318
sg115
VThu, 10 Jul 2014 15:50:01 +0000
p326
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2ac9v2/earrings_of_basilius/
p327
stRp328
ag1
(g2
g3
(dp329
S'summary_detail'
p330
g1
(g2
g3
(dp331
g9
Vhttp://www.reddit.com/r/DotA2.rss
p332
sg11
g54
sg13
Nsg14
V<!-- SC_OFF --><div class="md"><p>All games below are games I think are some of the must watch games amongst all the games today, due to upsets, close games, or player domination. Spoiler free! <a href="http://www.dota2.com/international/watch/July9/">Games are currently on the TI website. Just make sure you don't click anything that will spoil the game for you!</a> </p> <table><thead> <tr> <th>Team</th> <th>vs.</th> <th>Team</th> <th>Series # Game #</th> </tr> </thead><tbody> <tr> <td><a href="http://www.reddit.com/logo-titan"></a> Titan</td> <td>vs.</td> <td><a href="http://www.reddit.com/logo-newbee"></a> Newbee</td> <td>Series 10 Game 4</td> </tr> <tr> <td><a href="http://www.reddit.com/logo-arrow"></a> Arrow</td> <td>vs.</td> <td><a href="http://www.reddit.com/logo-dk"></a> DK</td> <td>Series 11 Game 3</td> </tr> <tr> <td><a href="http://www.reddit.com/logo-titan"></a> Titan</td> <td>vs.</td> <td><a href="http://www.reddit.com/logo-navi"></a> Navi</td> <td>Series 12 Game 2</td> </tr> <tr> <td><a href="http://www.reddit.com/logo-lgd"></a> LGD</td> <td>vs.</td> <td><a href="http://www.reddit.com/logo-liquid"></a> Liquid</td> <td>Series 14 Game 1</td> </tr> <tr> <td><a href="http://www.reddit.com/logo-nar"></a> Narvi</td> <td>vs.</td> <td><a href="http://www.reddit.com/logo-ig"></a> iG</td> <td>Series 14 Game 2</td> </tr> <tr> <td><a href="http://www.reddit.com/logo-dk"></a> DK</td> <td>vs.</td> <td><a href="http://www.reddit.com/logo-empire"></a> Empire</td> <td>Series 16 Game 1</td> </tr> <tr> <td><a href="http://www.reddit.com/logo-newbee"></a> Newbee</td> <td>vs.</td> <td><a href="http://www.reddit.com/logo-vg"></a> Vici</td> <td>Series 17 Game 1</td> </tr> <tr> <td><a href="http://www.reddit.com/logo-arrow"></a> Arrow</td> <td>vs.</td> <td><a href="http://www.reddit.com/logo-nar"></a> Narvi</td> <td>Series 17 Game 2</td> </tr> <tr> <td><a href="http://www.reddit.com/logo-fnatic"></a> Fnatic</td> <td>vs.</td> <td><a href="http://www.reddit.com/logo-alliance"></a> Alliance</td> <td>Series 17 Game 4</td> </tr> <tr> <td><a href="http://www.reddit.com/logo-liquid"></a> Liquid</td> <td>vs.</td> <td><a href="http://www.reddit.com/logo-arrow"></a> Arrow</td> <td>Series 18 Game 2</td> </tr> </tbody></table> <p>Enjoy these games! I will do the same tomorrow if people would like.</p> </div><!-- SC_ON --> submitted by <a href="http://www.reddit.com/user/brandoi"> brandoi </a> <br /> <a href="http://www.reddit.com/r/DotA2/comments/2ae9yi/the_international_2014_day_3_must_watch_games/">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2ae9yi/the_international_2014_day_3_must_watch_games/">[66 comments]</a>
p333
stRp334
sg19
(lp335
g1
(g2
g3
(dp336
g22
Vhttp://www.reddit.com/r/DotA2/comments/2ae9yi/the_international_2014_day_3_must_watch_games/
p337
sg11
g24
sg25
g26
stRp338
asg105
g106
((I2014
I7
I11
I3
I44
I51
I4
I192
I0
t(dtRp339
sg36
VThe International 2014 Day 3 Must Watch Games
p340
sg109
g333
sg110
I00
sS'title_detail'
p341
g1
(g2
g3
(dp342
g9
Vhttp://www.reddit.com/r/DotA2.rss
p343
sg11
g12
sg13
Nsg14
g340
stRp344
sg37
g337
sg115
VFri, 11 Jul 2014 03:44:51 +0000
p345
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2ae9yi/the_international_2014_day_3_must_watch_games/
p346
stRp347
ag1
(g2
g3
(dp348
S'summary_detail'
p349
g1
(g2
g3
(dp350
g9
Vhttp://www.reddit.com/r/DotA2.rss
p351
sg11
g54
sg13
Nsg14
Vsubmitted by <a href="http://www.reddit.com/user/okokok1233"> okokok1233 </a> <br /> <a href="https://www.youtube.com/watch?v=2o60pW091NU">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2aczwh/bulbaeveryone_flamed_us/">[262 comments]</a>
p352
stRp353
sg19
(lp354
g1
(g2
g3
(dp355
g22
Vhttp://www.reddit.com/r/DotA2/comments/2aczwh/bulbaeveryone_flamed_us/
p356
sg11
g24
sg25
g26
stRp357
asg105
g106
((I2014
I7
I10
I19
I53
I49
I3
I191
I0
t(dtRp358
sg36
VBulba:"Everyone flamed us"
p359
sg109
g352
sg110
I00
sS'title_detail'
p360
g1
(g2
g3
(dp361
g9
Vhttp://www.reddit.com/r/DotA2.rss
p362
sg11
g12
sg13
Nsg14
g359
stRp363
sg37
g356
sg115
VThu, 10 Jul 2014 12:53:49 -0700
p364
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2aczwh/bulbaeveryone_flamed_us/
p365
stRp366
ag1
(g2
g3
(dp367
S'summary_detail'
p368
g1
(g2
g3
(dp369
g9
Vhttp://www.reddit.com/r/DotA2.rss
p370
sg11
g54
sg13
Nsg14
Vsubmitted by <a href="http://www.reddit.com/user/Speyedur"> Speyedur </a> <br /> <a href="http://cloud-4.steampowered.com/ugc/582405046292771869/6861E6224CEB6C8299555C3E527087144E81F384/">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2adbwa/new_players_when_watching_in_game_clicking_on_an/">[38 comments]</a>
p371
stRp372
sg19
(lp373
g1
(g2
g3
(dp374
g22
Vhttp://www.reddit.com/r/DotA2/comments/2adbwa/new_players_when_watching_in_game_clicking_on_an/
p375
sg11
g24
sg25
g26
stRp376
asg105
g106
((I2014
I7
I10
I21
I46
I38
I3
I191
I0
t(dtRp377
sg36
VNew Players: when watching in game, clicking on an ability during a draft shows you what the ability does with a cool little video!
p378
sg109
g371
sg110
I00
sS'title_detail'
p379
g1
(g2
g3
(dp380
g9
Vhttp://www.reddit.com/r/DotA2.rss
p381
sg11
g12
sg13
Nsg14
g378
stRp382
sg37
g375
sg115
VThu, 10 Jul 2014 21:46:38 +0000
p383
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2adbwa/new_players_when_watching_in_game_clicking_on_an/
p384
stRp385
ag1
(g2
g3
(dp386
S'summary_detail'
p387
g1
(g2
g3
(dp388
g9
Vhttp://www.reddit.com/r/DotA2.rss
p389
sg11
g54
sg13
Nsg14
V<!-- SC_OFF --><div class="md"><p>I like commentator camera control but sometimes I want to click on heroes/units or check out a spot on the map real quick. It's a pain to use the drop-down list to switch back and forth.</p> </div><!-- SC_ON --> submitted by <a href="http://www.reddit.com/user/wrathgiver"> wrathgiver </a> <br /> <a href="http://www.reddit.com/r/DotA2/comments/2adz93/valve_spectating_please_add_a_button_that/">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2adz93/valve_spectating_please_add_a_button_that/">[29 comments]</a>
p390
stRp391
sg19
(lp392
g1
(g2
g3
(dp393
g22
Vhttp://www.reddit.com/r/DotA2/comments/2adz93/valve_spectating_please_add_a_button_that/
p394
sg11
g24
sg25
g26
stRp395
asg105
g106
((I2014
I7
I11
I1
I45
I46
I4
I192
I0
t(dtRp396
sg36
VValve: Spectating: Please add a button that switches to Free Camera mode while the button is held.
p397
sg109
g390
sg110
I00
sS'title_detail'
p398
g1
(g2
g3
(dp399
g9
Vhttp://www.reddit.com/r/DotA2.rss
p400
sg11
g12
sg13
Nsg14
g397
stRp401
sg37
g394
sg115
VFri, 11 Jul 2014 01:45:46 +0000
p402
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2adz93/valve_spectating_please_add_a_button_that/
p403
stRp404
ag1
(g2
g3
(dp405
S'summary_detail'
p406
g1
(g2
g3
(dp407
g9
Vhttp://www.reddit.com/r/DotA2.rss
p408
sg11
g54
sg13
Nsg14
V<!-- SC_OFF --><div class="md"><h3>The International 2014</h3> <h2>Organized and hosted by Valve Corporation</h2> <h2>Sponsored by Valve Corporation, The Compendium</h2> <hr /> <p><strong>Need info on the event? Check out our <a href="http://www.reddit.com/r/DotA2/wiki/events/ti4">Survival Guide</a></strong></p> <p><strong>Check out the Day 3 <a href="http://www.reddit.com/r/DotA2/comments/2ac6qf/the_international_2014_playoffs_day_3_match/">Live Discussion</a>.</strong></p> <h4>VODs can be found on the Watch tab of the TI Tournament Site</h4> <h3><a href="http://www.dota2.com/international/watch/July10/">Click &quot;Stream Navigation&quot; for a full list of Today's Games</a></h3> <hr /> <p>Well hello there! With the conclusion of Day 3 we find ourselves playing a little bit over half of the round robin games. The standings are developing, but with many more games to be played everything is still in flux. into Today we were blessed with another 12 hours of dota, most of which had four games going on simultaneously. We had a total of 36 games played between the 16 teams who made it to groups. This thread will serve as a recap of must watch games, cool stats, and general discussion. </p> <hr /> <h3>Standings after Day 3:</h3> <table><thead> <tr> <th align="left">Round Robin</th> <th align="center"><a href="http://www.reddit.com/nbsp"></a></th> <th align="center">Tentative Placing</th> </tr> </thead><tbody> <tr> <td align="left"><a href="http://www.reddit.com/cn" title="China"></a> <strong>Vici Gaming</strong></td> <td align="center">7-1</td> <td align="center">Team advances to Main Event's WB</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/cn" title="China"></a> <strong>Invictus Gaming</strong></td> <td align="center">6-3</td> <td align="center"></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/cn" title="China"></a> <strong>Team DK</strong></td> <td align="center">6-3</td> <td align="center">Team advances to 3rd phase round 3</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/us" title="United States"></a> <strong>Evil Geniuses</strong></td> <td align="center">6-3</td> <td align="center"></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/ua" title="Ukraine"></a> <strong>Natus Vincere</strong></td> <td align="center">5-3</td> <td align="center">Team advances to 3rd phase round 2</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/my" title="Malaysia"></a> <strong>Titan</strong></td> <td align="center">5-4</td> <td align="center"></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/us" title="United States"></a> <strong>Team Liquid</strong></td> <td align="center">5-4</td> <td align="center">Team advances to 3rd phase round 1</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/wo" title="World"></a> <strong>Cloud 9</strong></td> <td align="center">5-4</td> <td align="center"></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/cn" title="China"></a> <strong>Newbee</strong></td> <td align="center">5-5</td> <td align="center"></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/se" title="Sweden"></a> <strong>Alliance</strong></td> <td align="center">4-5</td> <td align="center"></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/us" title="United States"></a> <strong>Na'Vi North America</strong></td> <td align="center">4-5</td> <td align="center">Team is eliminated</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/eu" title="Europe"></a> <strong>Fnatic</strong></td> <td align="center">4-5</td> <td align="center"></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/cn" title="China"></a> <strong>LGD Gaming</strong></td> <td align="center">3-6</td> <td align="center"></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/ru" title="Russia"></a> <strong>Team Empire</strong></td> <td align="center">3-6</td> <td align="center"></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/de" title="Germany"></a> <strong>mousesports</strong></td> <td align="center">2-7</td> <td align="center"></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/my" title="Malaysia"></a> <strong>Arrow Gaming</strong></td> <td align="center">2-8</td> <td align="center"></td> </tr> </tbody></table> <hr /> <h3>Games to watch from Day 3:</h3> <p><strong><a href="http://www.dota2.com/international/watch/July9/">You can watch ALL match vods directly on the offical TI4 site. Click here to see them all</a>. You can also watch the games ingame, which is why we have provided matchIDs!</strong><br /> Now I know you might not be interested in watching 36 games. That is a metric-shit-ton of content. Here are some highlighted games to check out. The best of the best. The crème. The upper class of day 3.</p> <table><thead> <tr> <th align="center">Team 1</th> <th>vs</th> <th align="center">Team 2</th> <th align="center">matchID</th> </tr> </thead><tbody> <tr> <td align="center"><a href="http://www.reddit.com/logo-nar"></a></td> <td>vs</td> <td align="center"><a href="http://www.reddit.com/logo-ig"></a></td> <td align="center">769199481</td> </tr> <tr> <td align="center"><a href="http://www.reddit.com/logo-liquid"></a></td> <td>vs</td> <td align="center"><a href="http://www.reddit.com/logo-fnatic"></a></td> <td align="center">768808772</td> </tr> <tr> <td align="center"><a href="http://www.reddit.com/logo-nar"></a></td> <td>vs</td> <td align="center"><a href="http://www.reddit.com/logo-arrow"></a></td> <td align="center">769371854</td> </tr> <tr> <td align="center"><a href="http://www.reddit.com/logo-arrow"></a></td> <td>vs</td> <td align="center"><a href="http://www.reddit.com/logo-liquid"></a></td> <td align="center">769408915</td> </tr> <tr> <td align="center"><a href="http://www.reddit.com/logo-empire"></a></td> <td>vs</td> <td align="center"><a href="http://www.reddit.com/logo-dk"></a></td> <td align="center">769287352</td> </tr> <tr> <td align="center"><a href="http://www.reddit.com/logo-c9"></a></td> <td>vs</td> <td align="center"><a href="http://www.reddit.com/logo-navi"></a></td> <td align="center">768904872</td> </tr> <tr> <td align="center"><a href="http://www.reddit.com/logo-vg"></a></td> <td>vs</td> <td align="center"><a href="http://www.reddit.com/logo-newbee"></a></td> <td align="center">769348520</td> </tr> <tr> <td align="center"><a href="http://www.reddit.com/logo-arrow"></a></td> <td>vs</td> <td align="center"><a href="http://www.reddit.com/logo-dk"></a></td> <td align="center">768917747</td> </tr> </tbody></table> <p>While all these games are A++, this list is sorted with the &quot;best&quot; at the top. If you're pressed for time watch in order. Obviously there is no bias present. </p> <p>Are you sad that I did not list your favorite game here? Maybe I missed it. Please share your favorite match of Day 2 below! </p> <h3>Stats n' Stuff:</h3> <p>Here is a list of heroes who have not been picked through Day 2 of competition: </p> <table><thead> <tr> <th align="center">Str</th> <th align="center">Agi</th> <th align="center">Int</th> </tr> </thead><tbody> <tr> <td align="center"><a href="http://www.reddit.com/hero-omniknight"></a></td> <td align="center"><a href="http://www.reddit.com/hero-medusa"></a></td> <td align="center"><a href="http://www.reddit.com/hero-crystalmaiden"></a></td> </tr> <tr> <td align="center"><a href="http://www.reddit.com/hero-huskar"></a></td> <td align="center"><a href="http://www.reddit.com/hero-bountyhunter"></a></td> <td align="center"><a href="http://www.reddit.com/hero-lina"></a></td> </tr> <tr> <td align="center"><a href="http://www.reddit.com/hero-undying"></a></td> <td align="center"><a href="http://www.reddit.com/hero-phantomlancer"></a></td> <td align="center"><a href="http://www.reddit.com/hero-keeperofthelight"></a></td> </tr> <tr> <td align="center"><a href="http://www.reddit.com/hero-pudge"></a></td> <td align="center"><a href="http://www.reddit.com/hero-bloodseeker"></a></td> <td align="center"></td> </tr> <tr> <td align="center"><a href="http://www.reddit.com/hero-slardar"></a></td> <td align="center"><a href="http://www.reddit.com/hero-shadowfiend"></a></td> <td align="center"></td> </tr> <tr> <td align="center"><a href="http://www.reddit.com/hero-spiritbreaker"></a></td> <td align="center"><a href="http://www.reddit.com/hero-meepo"></a></td> <td align="center"></td> </tr> <tr> <td align="center"><a href="http://www.reddit.com/hero-nightstalker"></a></td> <td align="center"></td> <td align="center"></td> </tr> </tbody></table> <p>Fun tidbits: </p> <table><thead> <tr> <th align="center">What?</th> <th align="center">Who?</th> <th align="center">How much?</th> <th align="center">Info</th> </tr> </thead><tbody> <tr> <td align="center">Most Picked</td> <td align="center"><a href="http://www.reddit.com/hero-skywrathmage"></a></td> <td align="center">26</td> <td align="center">35% Winrate (9-17)</td> </tr> <tr> <td align="center">Most Banned</td> <td align="center"><a href="http://www.reddit.com/hero-lycan"></a></td> <td align="center">33</td> <td align="center">Picked in remaining 3 games</td> </tr> <tr> <td align="center">Most Successful (min 5 games)</td> <td align="center"><a href="http://www.reddit.com/hero-shadowshaman"></a></td> <td align="center">-</td> <td align="center">71% Winrate (10-4)</td> </tr> <tr> <td align="center">Least Successful (min 5 games)</td> <td align="center"><a href="http://www.reddit.com/hero-viper"></a></td> <td align="center">-</td> <td align="center">14% Winrate (1-6)</td> </tr> <tr> <td align="center">Best GPM</td> <td align="center"><a href="http://www.reddit.com/logo-nar" title="Na'Vi.US"></a> <strong>Sneyking</strong> <a href="http://www.reddit.com/hero-nagasiren"></a></td> <td align="center">817</td> <td align="center">versus <a href="http://www.reddit.com/logo-ig" title="Invictus Gaming"></a></td> </tr> <tr> <td align="center">Best KDA</td> <td align="center"><a href="http://www.reddit.com/logo-arrow" title="Arrow Gaming"></a> <strong>Lance</strong> <a href="http://www.reddit.com/hero-mirana"></a></td> <td align="center">13-1</td> <td align="center">versus <a href="http://www.reddit.com/logo-nar" title="Na'Vi.US"></a></td> </tr> <tr> <td align="center">Most Deaths</td> <td align="center"><a href="http://www.reddit.com/logo-nar"></a> <strong>1437</strong> <a href="http://www.reddit.com/hero-skywrathmage"></a></td> <td align="center">7-16</td> <td align="center">versus <a href="http://www.reddit.com/logo-ig"></a></td> </tr> <tr> <td align="center">Longest Game</td> <td align="center"><a href="http://www.reddit.com/logo-arrow"></a></td> <td align="center">73.07 minutes</td> <td align="center">versus <a href="http://www.reddit.com/logo-dk"></a></td> </tr> <tr> <td align="center">Shortest Game</td> <td align="center"><a href="http://www.reddit.com/logo-lgd"></a></td> <td align="center">17.52 minutes</td> <td align="center">versus <a href="http://www.reddit.com/logo-vg"></a></td> </tr> <tr> <td align="center">Fantasy Leader</td> <td align="center"><a href="http://www.reddit.com/logo-dk"></a> <strong>Mushi</strong></td> <td align="center">57</td> <td align="center">&lt;3</td> </tr> <tr> <td align="center">Best fantasy team score</td> <td align="center"><a href="http://www.reddit.com/logo-dk"></a> <strong>DK</strong></td> <td align="center">243.8</td> <td align="center"><a href="http://www.reddit.com/logo-ig"></a> when / games played</td> </tr> <tr> <td align="center">Minutes of dota played today</td> <td align="center">-</td> <td align="center">1432.06</td> <td align="center">That's just shy of 24hrs.</td> </tr> </tbody></table> <p>The best possible fantasy team today would have been a full DK roster, except Deamon sneaks in to replace MMY. Deamon is classified as a support even though he has been playing offlane, so that is an issue that should be addressed. Mushi (57), Iceiceice (56.6), Burning (53.1), LaNM (42.6) &amp; Pegasus (41.7) = 251. </p> <p><em>How many fantasy points did you score today?</em> </p> <p><a href="http://www.datdota.com/tournament.php?q=285&amp;tournament=The%20International%202014%3EThe%20International">I want more sexy TI4 Stats.</a><br /> <a href="https://docs.google.com/spreadsheets/d/1PsDzbVMQ2a_mDUyXTg63tZ2mvjC9TicWdhhzYMPC0eY/edit?usp=sharing">I want more sexy Fantasy Stats.</a> </p> <hr /> <p>So how did you feel about day 3? Were you overwhelmed with awesome games and the copious amount of content? Here are some talking-points for us:</p> <ul> <li>Are you still watching multicast with Bruno, or do you prefer to have more control over which games you're watching? </li> <li>Which team do you feel has disappointed you the most today?<br /></li> <li>Which team were you pleasantly surprised by today?<br /></li> <li>Will any of the bottom 6 teams make make it out of the trench on day 4? If so who will be falling down?<br /></li> <li>What hero do you want to see more of?<br /></li> <li>Are liquid <em>still</em> doing it? Will they make it to the main event?<br /></li> <li>Will Arrow finish in 14th or higher and earn some of that sweet dirty valve cash?<br /></li> <li>Are you sitting on <a href="http://www.reddit.com/r/dota2">/r/dota2</a> while watching these games? Any feedback for us or ideas for new content?<br /></li> </ul> <p>Get hyped for day 4 everyone. </p> <hr /> <h3>Full Results:</h3> <p><strong><a href="http://wiki.teamliquid.net/dota2/The_International/2014/Playoffs/Phase_Two">Check out the Liquipedia TI4 page for even more infromation and easier viewing</a></strong> </p> <table><thead> <tr> <th align="left">Team</th> <th align="center">&nbsp; vs. &nbsp;</th> <th align="center">Team</th> <th align="center">Casters</th> <th align="center">Result</th> </tr> </thead><tbody> <tr> <td align="left">-</td> <td align="center">-</td> <td align="center">-</td> <td align="center">-</td> <td align="center">-</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-ig" title="Invictus Gaming"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-mouz" title="Mousesports"></a></td> <td align="center">LD + Lumi</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-liquid" title="Team Liquid"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-fnatic" title="Fnatic"></a></td> <td align="center">Toby + Syn</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-nar" title="Na'Vi.US"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-empire" title="Empire"></a></td> <td align="center">Merlini + Godz</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="0-1"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-titan" title="Titan"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-newbee" title="Newbee"></a></td> <td align="center">Maut + KOTL Guy</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> <tr> <td align="left">-</td> <td align="center">-</td> <td align="center">-</td> <td align="center">-</td> <td align="center">-</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-ig" title="Invictus Gaming"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-eg" title="Evil Geniuses"></a></td> <td align="center">LD + Lumi</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-c9" title="Cloud9"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-navi" title="Na'Vi.EU"></a></td> <td align="center">Toby + Syn</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="0-1"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-arrow" title="Arrow Gaming"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-dk" title="Team DK"></a></td> <td align="center">Merlini + Godz</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="0-1"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-lgd" title="LGD"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-vg" title="Vici Gaming"></a></td> <td align="center">Maut + KOTL Guy</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="0-1"></a></td> </tr> <tr> <td align="left">-</td> <td align="center">-</td> <td align="center">-</td> <td align="center">-</td> <td align="center">-</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-lgd" title="LGD"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-fnatic" title="Fnatic"></a></td> <td align="center">LD + Lumi</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-titan" title="Titan"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-navi" title="Na'Vi.EU"></a></td> <td align="center">Toby + Syn</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-mouz" title="Mousesports"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-alliance" title="Alliance"></a></td> <td align="center">Merlini + Godz</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="0-1"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-vg" title="Vici Gaming"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-nar" title="Na'Vi.US"></a></td> <td align="center">Maut + KOTL Guy</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> <tr> <td align="left">-</td> <td align="center">-</td> <td align="center">-</td> <td align="center">-</td> <td align="center">-</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-empire" title="Empire"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-liquid" title="Team Liquid"></a></td> <td align="center">LD + Lumi</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="0-1"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-titan" title="Titan"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-arrow" title="Arrow Gaming"></a></td> <td align="center">Toby + Syn</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-dk" title="Team DK"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-c9" title="Cloud9"></a></td> <td align="center">Merlini + Godz</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-eg" title="Evil Geniuses"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-newbee" title="Newbee"></a></td> <td align="center">Maut + KOTL Guy</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> <tr> <td align="left">-</td> <td align="center">-</td> <td align="center">-</td> <td align="center">-</td> <td align="center">-</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-lgd" title="LGD"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-liquid" title="Team Liquid"></a></td> <td align="center">LD + Lumi</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-nar" title="Na'Vi.US"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-ig" title="Invictus Gaming"></a></td> <td align="center">Toby + Syn</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-mouz" title="Mousesports"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-dk" title="Team DK"></a></td> <td align="center">Lysander + Basskip</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="0-1"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-empire" title="Empire"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-alliance" title="Alliance"></a></td> <td align="center">Maut + KOTL Guy</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="0-1"></a></td> </tr> <tr> <td align="left">-</td> <td align="center">-</td> <td align="center">-</td> <td align="center">-</td> <td align="center">-</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-vg" title="Vici Gaming"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-fnatic" title="Fnatic"></a></td> <td align="center">LD + Lumi</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-c9" title="Cloud9"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-newbee" title="Newbee"></a></td> <td align="center">Toby + Syn</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="0-1"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-arrow" title="Arrow Gaming"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-mouz" title="Mousesports"></a></td> <td align="center">Lysander + Basskip</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="0-1"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-navi" title="Na'Vi.EU"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-eg" title="Evil Geniuses"></a></td> <td align="center">Capt+ Waga</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="0-1"></a></td> </tr> <tr> <td align="left">-</td> <td align="center">-</td> <td align="center">-</td> <td align="center">-</td> <td align="center">-</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-empire" title="Empire"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-dk" title="Team DK"></a></td> <td align="center">Ayesee + Malek</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="0-1"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-alliance" title="Alliance"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-nar" title="Na'Vi.US"></a></td> <td align="center">Merlini + Godz</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-liquid" title="Team Liquid"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-c9" title="Cloud9"></a></td> <td align="center">Lysander + Basskip</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="0-1"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-titan" title="Titan"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-ig" title="Invictus Gaming"></a></td> <td align="center">Capt+ Waga</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="0-1"></a></td> </tr> <tr> <td align="left">-</td> <td align="center">-</td> <td align="center">-</td> <td align="center">-</td> <td align="center">-</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-vg" title="Vici Gaming"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-newbee" title="Newbee"></a></td> <td align="center">Ayesee + Malek</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-nar" title="Na'Vi.US"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-arrow" title="Arrow Gaming"></a></td> <td align="center">Merlini + Godz</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="0-1"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-navi" title="Na'Vi.EU"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-lgd" title="LGD"></a></td> <td align="center">Lysander + Basskip</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-alliance" title="Alliance"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-fnatic" title="Fnatic"></a></td> <td align="center">Capt+ Waga</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="0-1"></a></td> </tr> <tr> <td align="left">-</td> <td align="center">-</td> <td align="center">-</td> <td align="center">-</td> <td align="center">-</td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-newbee" title="Newbee"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-mouz" title="Mousesports"></a></td> <td align="center">Ayesee + Malek</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-arrow" title="Arrow Gaming"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-liquid" title="Team Liquid"></a></td> <td align="center">Merlini + Godz</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-ig" title="Invictus Gaming"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-empire" title="Empire"></a></td> <td align="center">Lysander + Basskip</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="0-1"></a></td> </tr> <tr> <td align="left"><a href="http://www.reddit.com/logo-eg" title="Evil Geniuses"></a></td> <td align="center">vs.</td> <td align="center"><a href="http://www.reddit.com/logo-titan" title="Titan"></a></td> <td align="center">Capt+ Waga</td> <td align="center"><a href="http://www.reddit.com/r/DotA2.rss#s" title="1-0"></a></td> </tr> </tbody></table> </div><!-- SC_ON --> submitted by <a href="http://www.reddit.com/user/leafeator"> leafeator </a> <br /> <a href="http://www.reddit.com/r/DotA2/comments/2aedp1/the_international_2014_playoffs_day_3_results/">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2aedp1/the_international_2014_playoffs_day_3_results/">[27 comments]</a>
p409
stRp410
sg19
(lp411
g1
(g2
g3
(dp412
g22
Vhttp://www.reddit.com/r/DotA2/comments/2aedp1/the_international_2014_playoffs_day_3_results/
p413
sg11
g24
sg25
g26
stRp414
asg105
g106
((I2014
I7
I11
I4
I31
I2
I4
I192
I0
t(dtRp415
sg36
VThe International 2014 Playoffs Day 3: Results, Highlighted Games, Stats, & Discussion (Group's Day 2)
p416
sg109
g409
sg110
I00
sS'title_detail'
p417
g1
(g2
g3
(dp418
g9
Vhttp://www.reddit.com/r/DotA2.rss
p419
sg11
g12
sg13
Nsg14
g416
stRp420
sg37
g413
sg115
VFri, 11 Jul 2014 04:31:02 +0000
p421
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2aedp1/the_international_2014_playoffs_day_3_results/
p422
stRp423
ag1
(g2
g3
(dp424
S'summary_detail'
p425
g1
(g2
g3
(dp426
g9
Vhttp://www.reddit.com/r/DotA2.rss
p427
sg11
g54
sg13
Nsg14
V<!-- SC_OFF --><div class="md"><p>Hi!</p> <p>Do you have any feedback for <a href="http://wiki.teamliquid.net/dota2/The_International/2014">our The International 4 coverage</a>? Our goal is to provide useful information for teams, players, and of course all of the results. We're always greatful for feedback from our users.</p> <p>You are always welcome to help us with our coverage. The only thing you need is a LiquidDota.com account and you can jump right into editing. For more information see <a href="http://www.liquiddota.com/forum/dota-2-general/453864-lp-the-liquipedia-dota-2-wiki">here</a> and <a href="http://www.liquiddota.com/forum/website-feedback/455658-liquipedia-feedback-thread">here</a>.</p> </div><!-- SC_ON --> submitted by <a href="http://www.reddit.com/user/Liquipedia"> Liquipedia </a> <br /> <a href="http://www.reddit.com/r/DotA2/comments/2ad96y/with_ti4_going_on_weve_have_a_lot_of_visitors/">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2ad96y/with_ti4_going_on_weve_have_a_lot_of_visitors/">[139 comments]</a>
p428
stRp429
sg19
(lp430
g1
(g2
g3
(dp431
g22
Vhttp://www.reddit.com/r/DotA2/comments/2ad96y/with_ti4_going_on_weve_have_a_lot_of_visitors/
p432
sg11
g24
sg25
g26
stRp433
asg105
g106
((I2014
I7
I10
I21
I19
I55
I3
I191
I0
t(dtRp434
sg36
VWith TI4 going on, we've have a lot of visitors that are new to Liquipedia, so we're asking if you guys (new and old users) have any feedback about our TI4 coverage?
p435
sg109
g428
sg110
I00
sS'title_detail'
p436
g1
(g2
g3
(dp437
g9
Vhttp://www.reddit.com/r/DotA2.rss
p438
sg11
g12
sg13
Nsg14
g435
stRp439
sg37
g432
sg115
VThu, 10 Jul 2014 21:19:55 +0000
p440
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2ad96y/with_ti4_going_on_weve_have_a_lot_of_visitors/
p441
stRp442
ag1
(g2
g3
(dp443
S'summary_detail'
p444
g1
(g2
g3
(dp445
g9
Vhttp://www.reddit.com/r/DotA2.rss
p446
sg11
g54
sg13
Nsg14
V<!-- SC_OFF --><div class="md"><p>/s</p> </div><!-- SC_ON --> submitted by <a href="http://www.reddit.com/user/Another_year"> Another_year </a> <br /> <a href="http://www.reddit.com/r/DotA2/comments/2adxrs/attention_skywrath_mage_and_razor_picked_up_in/">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2adxrs/attention_skywrath_mage_and_razor_picked_up_in/">[120 comments]</a>
p447
stRp448
sg19
(lp449
g1
(g2
g3
(dp450
g22
Vhttp://www.reddit.com/r/DotA2/comments/2adxrs/attention_skywrath_mage_and_razor_picked_up_in/
p451
sg11
g24
sg25
g26
stRp452
asg105
g106
((I2014
I7
I11
I1
I29
I26
I4
I192
I0
t(dtRp453
sg36
VATTENTION: SKywrath Mage and Razor picked up in Alliance vs. Fnatic
p454
sg109
g447
sg110
I00
sS'title_detail'
p455
g1
(g2
g3
(dp456
g9
Vhttp://www.reddit.com/r/DotA2.rss
p457
sg11
g12
sg13
Nsg14
g454
stRp458
sg37
g451
sg115
VFri, 11 Jul 2014 01:29:26 +0000
p459
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2adxrs/attention_skywrath_mage_and_razor_picked_up_in/
p460
stRp461
ag1
(g2
g3
(dp462
S'summary_detail'
p463
g1
(g2
g3
(dp464
g9
Vhttp://www.reddit.com/r/DotA2.rss
p465
sg11
g54
sg13
Nsg14
Vsubmitted by <a href="http://www.reddit.com/user/teheditor"> teheditor </a> <br /> <a href="http://www.abc.net.au/technology/articles/2014/07/11/4044021.htm">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2adqw2/abc_covers_the_international_shows_all_main/">[25 comments]</a>
p466
stRp467
sg19
(lp468
g1
(g2
g3
(dp469
g22
Vhttp://www.reddit.com/r/DotA2/comments/2adqw2/abc_covers_the_international_shows_all_main/
p470
sg11
g24
sg25
g26
stRp471
asg105
g106
((I2014
I7
I11
I0
I17
I26
I4
I192
I0
t(dtRp472
sg36
VABC covers The International. Shows all main qualifiers.
p473
sg109
g466
sg110
I00
sS'title_detail'
p474
g1
(g2
g3
(dp475
g9
Vhttp://www.reddit.com/r/DotA2.rss
p476
sg11
g12
sg13
Nsg14
g473
stRp477
sg37
g470
sg115
VFri, 11 Jul 2014 00:17:26 +0000
p478
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2adqw2/abc_covers_the_international_shows_all_main/
p479
stRp480
ag1
(g2
g3
(dp481
S'summary_detail'
p482
g1
(g2
g3
(dp483
g9
Vhttp://www.reddit.com/r/DotA2.rss
p484
sg11
g54
sg13
Nsg14
Vsubmitted by <a href="http://www.reddit.com/user/datProtein"> datProtein </a> <br /> <a href="http://imgur.com/rVU3cwt">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2adhce/but_i_became_the_tiniest_one/">[80 comments]</a>
p485
stRp486
sg19
(lp487
g1
(g2
g3
(dp488
g22
Vhttp://www.reddit.com/r/DotA2/comments/2adhce/but_i_became_the_tiniest_one/
p489
sg11
g24
sg25
g26
stRp490
asg105
g106
((I2014
I7
I10
I22
I41
I0
I3
I191
I0
t(dtRp491
sg36
V"But I became the Tiniest one"
p492
sg109
g485
sg110
I00
sS'title_detail'
p493
g1
(g2
g3
(dp494
g9
Vhttp://www.reddit.com/r/DotA2.rss
p495
sg11
g12
sg13
Nsg14
g492
stRp496
sg37
g489
sg115
VThu, 10 Jul 2014 22:41:00 +0000
p497
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2adhce/but_i_became_the_tiniest_one/
p498
stRp499
ag1
(g2
g3
(dp500
S'summary_detail'
p501
g1
(g2
g3
(dp502
g9
Vhttp://www.reddit.com/r/DotA2.rss
p503
sg11
g54
sg13
Nsg14
Vsubmitted by <a href="http://www.reddit.com/user/Callik"> Callik </a> <br /> <a href="http://i.imgur.com/l7bTt7w.jpg">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2ae2ad/ti4_playoffs_phase_two_parity/">[25 comments]</a>
p504
stRp505
sg19
(lp506
g1
(g2
g3
(dp507
g22
Vhttp://www.reddit.com/r/DotA2/comments/2ae2ad/ti4_playoffs_phase_two_parity/
p508
sg11
g24
sg25
g26
stRp509
asg105
g106
((I2014
I7
I11
I2
I18
I32
I4
I192
I0
t(dtRp510
sg36
VTI4 - Playoffs Phase Two Parity
p511
sg109
g504
sg110
I00
sS'title_detail'
p512
g1
(g2
g3
(dp513
g9
Vhttp://www.reddit.com/r/DotA2.rss
p514
sg11
g12
sg13
Nsg14
g511
stRp515
sg37
g508
sg115
VFri, 11 Jul 2014 02:18:32 +0000
p516
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2ae2ad/ti4_playoffs_phase_two_parity/
p517
stRp518
ag1
(g2
g3
(dp519
S'summary_detail'
p520
g1
(g2
g3
(dp521
g9
Vhttp://www.reddit.com/r/DotA2.rss
p522
sg11
g54
sg13
Nsg14
V<!-- SC_OFF --><div class="md"><p>On the C9 vs NaVi game it was bad and Arrow vs DK had it too, though not as bad. It sounds like something is disrupting a wireless microphone connection.(experience)<br /> Anyone else experiencing this?</p> <p>EDIT: It got worse again, I'm okay with a bit of delay or something, but this is straight up torture. Not listening to casting until this is fixed.</p> </div><!-- SC_ON --> submitted by <a href="http://www.reddit.com/user/Double_DeluXe"> Double_DeluXe </a> <br /> <a href="http://www.reddit.com/r/DotA2/comments/2aclue/casts_are_full_of_digital_stutter_and_tearing/">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2aclue/casts_are_full_of_digital_stutter_and_tearing/">[124 comments]</a>
p523
stRp524
sg19
(lp525
g1
(g2
g3
(dp526
g22
Vhttp://www.reddit.com/r/DotA2/comments/2aclue/casts_are_full_of_digital_stutter_and_tearing/
p527
sg11
g24
sg25
g26
stRp528
asg105
g106
((I2014
I7
I10
I17
I45
I26
I3
I191
I0
t(dtRp529
sg36
VCasts are full of digital stutter and tearing
p530
sg109
g523
sg110
I00
sS'title_detail'
p531
g1
(g2
g3
(dp532
g9
Vhttp://www.reddit.com/r/DotA2.rss
p533
sg11
g12
sg13
Nsg14
g530
stRp534
sg37
g527
sg115
VThu, 10 Jul 2014 17:45:26 +0000
p535
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2aclue/casts_are_full_of_digital_stutter_and_tearing/
p536
stRp537
ag1
(g2
g3
(dp538
S'summary_detail'
p539
g1
(g2
g3
(dp540
g9
Vhttp://www.reddit.com/r/DotA2.rss
p541
sg11
g54
sg13
Nsg14
V<!-- SC_OFF --><div class="md"><p>Several games going all the way to the ancient. No real dominant team. What a show. What. A. Show.</p> </div><!-- SC_ON --> submitted by <a href="http://www.reddit.com/user/Spasticon"> Spasticon </a> <br /> <a href="http://www.reddit.com/r/DotA2/comments/2adjan/ti4_these_games_so_good/">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2adjan/ti4_these_games_so_good/">[168 comments]</a>
p542
stRp543
sg19
(lp544
g1
(g2
g3
(dp545
g22
Vhttp://www.reddit.com/r/DotA2/comments/2adjan/ti4_these_games_so_good/
p546
sg11
g24
sg25
g26
stRp547
asg105
g106
((I2014
I7
I10
I23
I0
I53
I3
I191
I0
t(dtRp548
sg36
VTI4 ... these games ... so good.
p549
sg109
g542
sg110
I00
sS'title_detail'
p550
g1
(g2
g3
(dp551
g9
Vhttp://www.reddit.com/r/DotA2.rss
p552
sg11
g12
sg13
Nsg14
g549
stRp553
sg37
g546
sg115
VThu, 10 Jul 2014 23:00:53 +0000
p554
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2adjan/ti4_these_games_so_good/
p555
stRp556
ag1
(g2
g3
(dp557
S'summary_detail'
p558
g1
(g2
g3
(dp559
g9
Vhttp://www.reddit.com/r/DotA2.rss
p560
sg11
g54
sg13
Nsg14
Vsubmitted by <a href="http://www.reddit.com/user/matrix325"> matrix325 </a> <br /> <a href="http://www.youtube.com/watch?v=vJpo324AfTE&amp;feature=youtu.be">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2aekgp/matchmaking_episode_3_xboct_dendi/">[15 comments]</a>
p561
stRp562
sg19
(lp563
g1
(g2
g3
(dp564
g22
Vhttp://www.reddit.com/r/DotA2/comments/2aekgp/matchmaking_episode_3_xboct_dendi/
p565
sg11
g24
sg25
g26
stRp566
asg105
g106
((I2014
I7
I11
I6
I2
I13
I4
I192
I0
t(dtRp567
sg36
VMatchmaking Episode 3 - XBOCT & Dendi
p568
sg109
g561
sg110
I00
sS'title_detail'
p569
g1
(g2
g3
(dp570
g9
Vhttp://www.reddit.com/r/DotA2.rss
p571
sg11
g12
sg13
Nsg14
g568
stRp572
sg37
g565
sg115
VFri, 11 Jul 2014 06:02:13 +0000
p573
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2aekgp/matchmaking_episode_3_xboct_dendi/
p574
stRp575
ag1
(g2
g3
(dp576
S'summary_detail'
p577
g1
(g2
g3
(dp578
g9
Vhttp://www.reddit.com/r/DotA2.rss
p579
sg11
g54
sg13
Nsg14
V<!-- SC_OFF --><div class="md"><p>Hi,</p> <p>I'm Chris and I know a bunch of you awesome folks at <a href="http://www.reddit.com/r/Dota2">/r/Dota2</a> have been listening to the <a href="http://www.audiodota.com">audio only streams on AudioDota.com</a>. I have a few exciting announcements.</p> <p><strong>First</strong>, we've gone from having only the multistream available to having Stream 1 and Stream 2 available as well. I'd love to have all four streams live, but I don't have the physical capabilities to provide more than 3 streams from my current location. I've had some amazing volunteers offer to help, so we will hopefully have all four streams up soon.</p> <p><strong>Second</strong>, some android users have had problems listening to the streams. It seems like an issue isolated to a few phones, and I'm going to be borrowing some android devices today to test these issues and get them resolved. Until then, the best solution is to download the <a href="https://play.google.com/store/apps/details?id=org.videolan.vlc.betav7neon">VLC for Android Beta</a>. Once it's installed, open the audio stream through VLC.</p> <p>There are three audio streams:</p> <ul> <li>MultiStream: <a href="http://dotaaudio.com:8000/DotaMultiMp3">http://dotaaudio.com:8000/DotaMultiMp3</a></li> <li>Stream 1: <a href="http://dotaaudio.com:8000/DotaStream1Mp3">http://dotaaudio.com:8000/DotaStream1Mp3</a></li> <li>Stream 2: <a href="http://dotaaudio.com:8000/DotaStream2Mp3">http://dotaaudio.com:8000/DotaStream2Mp3</a></li> </ul> <p>If these streams aren't working, feel free to send me a pm on reddit, post here, or contact me via email (my email address is on the site.) </p> <p><strong>Third</strong>, it looks like an android Dota app might soon be integrating the streams, creating a more seamless Dota 2 listening experience during The International 4. I'll let you know on reddit and on the site when the app is featuring the streams.</p> <p>Finally,</p> <p>Thanks for your support. I was quite worried about bandwidth costs going into this, but it looks like ads and a few generous donations through paypal and bitcoin have me almost breaking even by the end of TI4.</p> <p><strong>Edit</strong>: I'm heading out for a few hours. The stream's held up without a hitch today, which is blowing my mind. If the stream goes down, you need some help, or you just want to say hi, please contact me via <a href="http://twitter.com/ckinniburgh">twitter</a> so I can quickly respond to any issues! I'm <a href="http://twitter.com/ckinniburgh">@ckinniburgh</a>.</p> <p>Thanks for listening!</p> </div><!-- SC_ON --> submitted by <a href="http://www.reddit.com/user/Shalarn"> Shalarn </a> <br /> <a href="http://www.reddit.com/r/DotA2/comments/2aci3b/low_bandwidth_audio_only_streams_for_ti4/">[link]</a> <a href="http://www.reddit.com/r/DotA2/comments/2aci3b/low_bandwidth_audio_only_streams_for_ti4/">[74 comments]</a>
p580
stRp581
sg19
(lp582
g1
(g2
g3
(dp583
g22
Vhttp://www.reddit.com/r/DotA2/comments/2aci3b/low_bandwidth_audio_only_streams_for_ti4/
p584
sg11
g24
sg25
g26
stRp585
asg105
g106
((I2014
I7
I10
I17
I10
I18
I3
I191
I0
t(dtRp586
sg36
VLow Bandwidth Audio Only Streams for TI4
p587
sg109
g580
sg110
I00
sS'title_detail'
p588
g1
(g2
g3
(dp589
g9
Vhttp://www.reddit.com/r/DotA2.rss
p590
sg11
g12
sg13
Nsg14
g587
stRp591
sg37
g584
sg115
VThu, 10 Jul 2014 17:10:18 +0000
p592
sg117
Vhttp://www.reddit.com/r/DotA2/comments/2aci3b/low_bandwidth_audio_only_streams_for_ti4/
p593
stRp594
astRp595
.